// projects/vue/webcomponents-project/src/components/VueCardComponent.vue
<template>
  <vue-card-component
    title="Welcome from Vue WebComponent"
    :logo="logo"
    button="Log event from Vue.js!"
    @selectButton="selectButton"
  >
    <slot></slot>
  </vue-card-component>
</template>

<script>
import vueLogo from "../assets/logos/vue.svg";

export default {
  name: "VueCard",
  data: function() {
    return {
      logo: vueLogo
    };
  },
  methods: {
    selectButton(event) {
      // eslint-disable-next-line no-console
      console.log(event);
      this.$emit("onSelect", { details: { selectedLogo: vueLogo } });
    }
  }
};
</script>

// projects/react/webcomponents-project/src/components/vue/VueCardComponent.js
import React, { Component } from 'react';
import vueLogo from '../../logos/vue.svg';

class VueCardComponent extends Component {

  selectButton = event => {
    if (this.props.onSelect){
      this.props.onSelect(event, vueLogo);
    }
    console.log(event);
  }

  componentDidMount() {
    const vueElement = document.querySelector('vue-card-component');
    vueElement.addEventListener('selectButton', this.selectButton);
  }

  render() {
    return (
        <vue-card-component
            title="Welcome from Vue.js WebComponent"
            button="Log event from Vue.js!"
            logo={vueLogo}
        />
    );
  }
}

export default VueCardComponent;
