// components/react/react-card-component/src/styles.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  'card': {
    'maxWidth': [{ 'unit': '%H', 'value': 1 }],
    'width': [{ 'unit': '%H', 'value': 1 }],
    'borderRadius': '0.2em',
    'backgroundColor': 'rgb(228, 245, 239)',
    'boxShadow': [{ 'unit': 'px', 'value': 0 }, { 'unit': 'px', 'value': 3 }, { 'unit': 'px', 'value': 5 }, { 'unit': 'string', 'value': 'rgba(0,0,0,0.2)' }],
    'justifyContent': 'center',
    'textAlign': 'center',
    'color': 'black'
  },
  'title': {
    'borderBottom': [{ 'unit': 'px', 'value': 1 }, { 'unit': 'string', 'value': 'solid' }, { 'unit': 'string', 'value': '#0f0f0f' }]
  },
  'logo': {
    'height': [{ 'unit': 'rem', 'value': 3 }],
    'margin': [{ 'unit': 'rem', 'value': 0.5 }, { 'unit': 'rem', 'value': 0.5 }, { 'unit': 'rem', 'value': 0.5 }, { 'unit': 'rem', 'value': 0.5 }]
  },
  'header': {
    'justifyContent': 'center'
  },
  'footer': {
    'marginBottom': [{ 'unit': 'rem', 'value': 0.5 }]
  },
  'button': {
    'display': 'inline-block',
    'verticalAlign': 'middle',
    'fontFamily': 'inherit',
    'cursor': 'pointer',
    'userSelect': 'none',
    'position': 'relative',
    'boxSizing': 'border-box',
    'fontSize': [{ 'unit': 'px', 'value': 14 }],
    'lineHeight': [{ 'unit': 'px', 'value': 16 }],
    'height': [{ 'unit': 'px', 'value': 32 }],
    'WebkitTapHighlightColor': 'rgba(255, 255, 255, 0)',
    'borderWidth': 'initial',
    'borderStyle': 'none',
    'borderColor': 'initial',
    'borderImage': 'initial',
    'textDecoration': 'none',
    'borderRadius': '3px',
    'padding': [{ 'unit': 'px', 'value': 0 }, { 'unit': 'px', 'value': 14 }, { 'unit': 'px', 'value': 0 }, { 'unit': 'px', 'value': 14 }],
    'outline': '0px',
    'color': 'rgb(255, 255, 255)',
    'backgroundColor': 'rgb(66, 185, 131)',
    'margin': [{ 'unit': 'rem', 'value': 0.5 }, { 'unit': 'rem', 'value': 0.5 }, { 'unit': 'rem', 'value': 0.5 }, { 'unit': 'rem', 'value': 0.5 }]
  }
});

// components/lit/lit-card-component/src/components/styles.js
import { css } from 'lit-element';

export const Styles = css`
  .card {
    max-width: 100%;
    width: 100%;
    border-radius: 0.2em;
    background-color: rgb(228, 245, 239);
    box-shadow: 0 3px 5px rgba(0,0,0,0.2);
    justify-content: center;
    text-align: center;
    color: black;
  }
  .title {
  border-bottom: 1px solid #0f0f0f;
  }
  .logo {
    height: 3rem;
    margin: .5rem;
  }
  .footer {
    margin-bottom: .5rem;
  }
  .button {
    display: inline-block;
    vertical-align: middle;
    font-family: inherit;
    cursor: pointer;
    user-select: none;
    position: relative;
    box-sizing: border-box;
    font-size: 14px;
    line-height: 16px;
    height: 32px;
    -webkit-tap-highlight-color: rgba(255, 255, 255, 0);
    border-width: initial;
    border-style: none;
    border-color: initial;
    border-image: initial;
    text-decoration: none;
    border-radius: 3px;
    padding: 0px 14px;
    outline: 0px;
    color: rgb(255, 255, 255);
    background-color: rgb(66, 185, 131);
    margin: .5rem;
  }
`;
