// projects/react/webcomponents-project/src/components/react/HeaderComponent.js
import React, { Component } from 'react';
import reactLogo from '../../logos/react.svg';
import './styles.css';

class HeaderComponent extends Component {

  render() {
    const logoSrc = this.props.selectedLogo ? this.props.selectedLogo : reactLogo;
    return (
      <div className='wrapper'>
        <h1>Using WebComponents in React</h1>
        <h2>Selected</h2>
        <img className='mainLogo' src={logoSrc} />
      </div>
    );
  }
}

export default HeaderComponent;

// projects/angular/webcomponents-project/src/app/header/header.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  @Input() logo: string;

  constructor() { }

  ngOnInit() {
  }

}

  <div class="wrapper">
    <h1>Using WebComponents in Angular</h1>
    <h2>Selected</h2>
    <img class="mainLogo" [src]="logo"
   />
  </div>
