// projects/vue/webcomponents-project/src/components/HeaderComponent.vue
<template>
  <div class="wrapper">
    <h1>Using WebComponents in Vue.js</h1>
    <h2>Selected</h2>
    <img class="mainLogo" :src="logo" />
  </div>
</template>

<script>
export default {
  name: "HeaderComponent",
  props: {
    logo: String
  }
};
</script>

<style>
.wrapper {
  display: grid;
  justify-content: center;
  align-items: center;
  margin: 3rem;
  text-align: center;
}

.mainLogo {
  height: 7rem;
  justify-self: center;
}
</style>

// projects/react/webcomponents-project/src/components/react/HeaderComponent.js
import React, { Component } from 'react';
import reactLogo from '../../logos/react.svg';
import './styles.css';

class HeaderComponent extends Component {

  render() {
    const logoSrc = this.props.selectedLogo ? this.props.selectedLogo : reactLogo;
    return (
      <div className='wrapper'>
        <h1>Using WebComponents in React</h1>
        <h2>Selected</h2>
        <img className='mainLogo' src={logoSrc} />
      </div>
    );
  }
}

export default HeaderComponent;
