// projects/vue/webcomponents-project/src/components/ReactCardComponent.vue
<template>
  <react-card-component
    title="Welcome from React WebComponent"
    :logo="logo"
    button="Log event from React!"
    @onSelect="onSelect"
  >
    <slot></slot>
  </react-card-component>
</template>

<script>
import reactLogo from "../assets/logos/react.svg";

export default {
  name: "ReactCard",
  data: function() {
    return {
      logo: reactLogo
    };
  },
  methods: {
    onSelect(event) {
      // eslint-disable-next-line no-console
      console.log(event);
      this.$emit("onSelect", { details: { selectedLogo: reactLogo } });
    }
  }
};
</script>

// projects/react/webcomponents-project/src/components/react/ReactCardComponent.js
import React, { Component } from 'react';
import reactLogo from '../../logos/react.svg';

class ReactCardComponent extends Component {

  onSelect = event => {
    if (this.props.onSelect){
      this.props.onSelect(event, reactLogo);
    }
    console.log(event);
  }

  componentDidMount() {
    const cardComponent = document.getElementById('react-card-component');
    cardComponent.addEventListener('onSelect', this.onSelect);
  }

  render() {
    return (
        <react-card-component
            id="react-card-component"
            title="Welcome from React WebComponent"
            logo={reactLogo}
            button="Log event from React!"
        />
    );
  }
}

export default ReactCardComponent;
