// projects/lit/webcomponents-project/src/components/angular/angular-card.js
import { LitElement, html } from 'lit-element';
import '../../webcomponents/angular-card-component';

class AngularCard extends LitElement {
  static get properties() {
    return {
      onSelect: { type: Function }
    }
  }

  onSelect(event) {
    let customEvent = new CustomEvent('onClick', {
      detail: {
        logo: "./src/assets/logos/angular.svg"
      }
    });

    this.dispatchEvent(customEvent);
    console.log(event);
  }

  render() {
    return html`
        <angular-card-component
          title="Welcome from Angular WebComponent"
          logo="./src/assets/logos/angular.svg"
          button="Log event from Angular!"
          @onSelect=${this.onSelect}
        />
    `;
  }
}

window.customElements.define('angular-card', AngularCard);

// projects/angular/webcomponents-project/src/app/lit-card/lit-card.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-lit-card',
  templateUrl: './lit-card.component.html',
  styleUrls: ['./lit-card.component.scss']
})
export class LitCardComponent implements OnInit {
  @Output() select = new EventEmitter<any>();
  @Input() logo: string;

  constructor() {
    this.logo = '../../assets/logos/polymer.svg';
  }

  ngOnInit() {
  }

  selectEvent($event) {
    console.log($event);
    this.select.emit(this.logo);
  }
}

<lit-card-component
  title="Welcome from Lit WebComponent"
  [logo]="logo"
  button="Log event from Lit!"
  (onSelect)="selectEvent($event)"
></lit-card-component>
