// projects/vue/webcomponents-project/src/App.vue
<template>
  <div id="app">
    <HeaderComponent :logo="logo" />
    <VueCard @onSelect="onSelect" />
    <LitCard @onSelect="onSelect" />
    <ReactCard @onSelect="onSelect" />
    <AngularCard @onSelect="onSelect" />
  </div>
</template>

<script>
import VueCard from "./components/VueCardComponent.vue";
import LitCard from "./components/LitCardComponent.vue";
import ReactCard from "./components/ReactCardComponent.vue";
import AngularCard from "./components/AngularCardComponent.vue";
import HeaderComponent from "./components/HeaderComponent.vue";

import logo from "./assets/logos/vue.svg";

export default {
  name: "app",
  components: {
    HeaderComponent,
    VueCard,
    LitCard,
    ReactCard,
    AngularCard
  },
  data: function() {
    return {
      logo: logo
    };
  },
  methods: {
    onSelect(event) {
      this.logo = event.details.selectedLogo;
    }
  }
};
</script>

// projects/react/webcomponents-project/src/App.js
import React, { Component } from 'react';
import LitCardComponent from './components/litelement/LitCardComponent';
import ReactCardComponent from './components/react/ReactCardComponent';
import AngularCardComponent from './components/angular/AngularCardComponent';
import VueCardComponent from './components/vue/VueCardComponent';
import HeaderComponent from './components/react/HeaderComponent';

class App extends Component {
  state={
    selectedLogo: '',
  }

  onSelect = (event, logo) => {
    this.setState({selectedLogo: logo});
  }

  render() {
    return (
      <div>
        <HeaderComponent selectedLogo={this.state.selectedLogo} />
        <ReactCardComponent onSelect={this.onSelect} />
        <LitCardComponent onSelect={this.onSelect} />
        <VueCardComponent onSelect={this.onSelect} />
        <AngularCardComponent onSelect={this.onSelect} />
      </div>
    );
  }
}

export default App;
