// projects/react/webcomponents-project/src/components/angular/AngularCardComponent.js
import React, { Component } from 'react';
import angularLogo from '../../logos/angular.svg';

class AngularCardComponent extends Component {

  selectButton = event => {
    if (this.props.onSelect){
      this.props.onSelect(event, angularLogo);
    }
    console.log(event);
  }

  componentDidMount() {
    const myElement = document.querySelector('angular-card-component');
    myElement.addEventListener('selectButton', this.selectButton);
  }

  render() {
    return (
       <angular-card-component
          title="Welcome from Angular WebComponent"
          logo={angularLogo}
          button="Log event from Angular!"
        />
    );
  }
}

export default AngularCardComponent;

// projects/vue/webcomponents-project/src/components/AngularCardComponent.vue
<template>
  <angular-card-component
    title="Welcome from Angular WebComponent"
    :logo="logo"
    button="Log event from Angular!"
    @selectButton="selectButton"
  >
    <slot></slot>
  </angular-card-component>
</template>

<script>
import angularLogo from "../assets/logos/angular.svg";

export default {
  name: "AngularCard",
  data: function() {
    return {
      logo: angularLogo
    };
  },
  methods: {
    selectButton(event) {
      // eslint-disable-next-line no-console
      console.log(event);
      this.$emit("onSelect", { details: { selectedLogo: angularLogo } });
    }
  }
};
</script>
