// projects/lit/webcomponents-project/src/components/angular/angular-card.js
import { LitElement, html } from 'lit-element';
import '../../webcomponents/angular-card-component';

class AngularCard extends LitElement {
  static get properties() {
    return {
      onSelect: { type: Function }
    }
  }

  onSelect(event) {
    let customEvent = new CustomEvent('onClick', {
      detail: {
        logo: "./src/assets/logos/angular.svg"
      }
    });

    this.dispatchEvent(customEvent);
    console.log(event);
  }

  render() {
    return html`
        <angular-card-component
          title="Welcome from Angular WebComponent"
          logo="./src/assets/logos/angular.svg"
          button="Log event from Angular!"
          @onSelect=${this.onSelect}
        />
    `;
  }
}

window.customElements.define('angular-card', AngularCard);

// projects/angular/webcomponents-project/src/app/react-card/react-card.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-react-card',
  templateUrl: './react-card.component.html',
  styleUrls: ['./react-card.component.scss']
})
export class ReactCardComponent implements OnInit {
  @Output() select = new EventEmitter<string>();
  @Input() logo: string;

  constructor() {
    this.logo = '../../assets/logos/react.svg';
  }

  ngOnInit() {
  }

  selectEvent($event) {
    console.log($event);
    this.select.emit(this.logo);
  }
}

<react-card-component
  id="react-card-component"
  title="Welcome from React WebComponent"
  logo="../../assets/logos/react.svg"
  button="Log event from React!"
  (onSelect)="selectEvent($event)"
></react-card-component>
