// projects/vue/webcomponents-project/src/components/LitCardComponent.vue
<template>
  <lit-card-component
    title="Welcome from Lit WebComponent"
    :logo="logo"
    button="Log event from Lit!"
    @selectButton="selectButton"
  >
    <slot></slot>
  </lit-card-component>
</template>

<script>
import polymerLogo from "../assets/logos/polymer.svg";

export default {
  name: "LitCard",
  data: function() {
    return {
      logo: polymerLogo
    };
  },
  methods: {
    selectButton(event) {
      // eslint-disable-next-line no-console
      console.log(event);
      this.$emit("onSelect", { details: { selectedLogo: polymerLogo } });
    }
  }
};
</script>

// projects/react/webcomponents-project/src/components/litelement/LitCardComponent.js
import React, { Component } from 'react';
import polymerLogo from '../../logos/polymer.svg';

class LitCardComponent extends Component {

  selectButton = event => {
    if (this.props.onSelect){
      this.props.onSelect(event, polymerLogo);
    }
    console.log(event);
  }

  componentDidMount() {
    const myElement = document.querySelector('lit-card-component');
    myElement.addEventListener('selectButton', this.selectButton);
  }

  render() {
    return (
      <div className="card">
        <lit-card-component
          title="Welcome from Lit WebComponent"
          logo={polymerLogo}
          button="Log event from Lit!"
        />
      </div>
    );
  }
}

export default LitCardComponent;
