// components/lit/lit-card-component/src/components/card-component.js
import { LitElement, html } from 'lit-element';
import { Styles } from './styles.js';

class CardComponent extends LitElement {

  static get properties() {
    return {
      title: { type: String },
      body: { type: String },
      button: { type: String },
      logo: { type: String }
    }
  }

  static get styles() {
    return [ Styles ];
  }

  onClick() {
    this.dispatchEvent(new CustomEvent('onSelect'));
  }

  render() {
    return html`
        <div class="card">
        <div class="header">
          <img alt="Logo" class="logo" src=${this.logo} />
          <div class="title">
            ${this.title}
          </div>
        </div>
        <div class="body">
          ${this.body}
        </div>
        <div class="footer">
          <button class="button" @click=${this.onClick}>
            ${this.button}
          </button>
        </div>
      </div>
    `;
  }
}

window.customElements.define('lit-card-component', CardComponent);

// components/react/react-card-component/src/CardComponent.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import root from 'react-shadow';
import classNames from 'classnames';
import styles from './styles.css'

class CardComponent extends Component {
  //Should be provided for the component to be correctly converted to a web-component
  static propTypes = {
    title: PropTypes.string,
    logo: PropTypes.string,
    body: PropTypes.string,
    button: PropTypes.string,
    className: PropTypes.string,
    onSelect: PropTypes.func
  }

  static defaultProps = {
    title: '',
    logo: '',
    body: '',
    button: '',
    className: ''
  }

  constructor() {
    super();
  }

  render() {
    const { logo, title, body, button, onSelect, className } = this.props;

    return (
      <root.div>
        <div className={classNames(className && className.card, 'card')}>
            <div className={classNames(className && className.header, 'header')}>
              <img alt='Logo' className={classNames(className && className.logo, 'logo')} src={logo} />
              <div className={classNames(className && className.title, 'title')}>
                {title}
              </div>
            </div>
            <div className={classNames(className && className.body, 'body')}>
              {body}
            </div>
            <div className={classNames(className && className.footer, 'footer')}>
              <button className={classNames(className && className.button, 'button')} onClick={onSelect} >
                {button}
              </button>
            </div>
            <style type="text/css">{styles}</style>
            <style type="text/css">{className}</style>
        </div>
      </root.div>
    );
  }
}

export default CardComponent;
